version: "3.8"

services:
  hypro-predict:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - hypro/predict_server:${PRED_VERSION}
    image: hypro/predict_server:${PRED_VERSION}
    container_name: hypro-predict
    restart: unless-stopped
    ports:
      - "80:${PRED_PORT}"
    volumes:
      # Mount the server_logs directory to the container
      - type: bind
        source: ${PRED_LOG_FOLDER}
        target: /app/server_logs
      # Mount the trained_models directory to the container
      - type: bind
        source: ${PRED_MODEL_FOLDER}
        target: /app/trained_models
